#PBS -l walltime=96:00:00,nodes=1:ppn=1
#PBS -S /bin/bash
#PBS -j eo
#PBS -N stemKernel-homo-ttp

export DIRECTORY=/home/bhandare/workspace/stem_kernel-296a

JOBIDONLY=${PBS_JOBID%%.ncar-loginmgt}

cd $DIRECTORY
cd stem_kernel_lite

#Train the model.
./stem_kernel_lite --pf-scale -n emmons_2008_one_transcript_per_gene_3utr.dat +1 /projects/debra/workspace/Data/TTP/Homo/Data/Emmons_2008/Emmons_2008_3UTRs_OneTranscriptPerGene.txt -1  /projects/debra/workspace/Data/TTP/Homo/Data/Random/random250Homo3UTRSequences.txt

./stem_kernel_lite --pf-scale -n emmons_2008_longest_transcript_per_gene_3utr.dat +1 /projects/debra/workspace/Data/TTP/Homo/Data/Emmons_2008/Emmons_2008_LongestTranscriptPerGene_3UTR.txt -1  /projects/debra/workspace/Data/TTP/Homo/Data/Random/random350Homo3UTRSequences.txt
