COMBINED_TRAIN_FILE_NAME=$(wildcard GSM*train*CompleteSet.txt)
COMBINED_TEST_FILE_NAME=$(wildcard GSM*test*CompleteSet.txt)

CONF_TRAIN_PREFIX=TTP_InDomain_Train
CONF_TEST_PREFIX=TTP_InDomain_Test

TRAIN_RESULTS_YML=$(CONF_TRAIN_PREFIX)_Results.yml
TEST_RESULTS_FILE=$(CONF_TEST_PREFIX)_Results.yml
TEST_FEATURES_FILE=$(CONF_TEST_PREFIX)_Features.txt
MODEL_FILE_NAME=$(CONF_TRAIN_PREFIX)_Model.dat
TEST_SPECTRUM_FILE=$(CONF_TEST_PREFIX)_kspectrum.dat


TEST_MODEL_SCRIPT=/projects/bhandare/workspace/kernels/k-spectrum/scripts/InDomainTest.py
COMBINED_MODEL_SCRIPT=/projects/bhandare/workspace/scripts/WeightVector/createCombinedModel.py

PREFIX=TTP
DOMAIN_PRIME_FILE=$(PREFIX)_InDomain_Test_Prime_kspectrum.dat
DOMAIN_OUTPUT_FILE=$(PREFIX)_WithDomain_Test_kspectrum.dat

all: step3 step4
.PHONY: all

step3:
	@echo "**** STEP 6: TEST MODEL ****: $(COMBINED_TEST_FILE_NAME)"	
	python $(TEST_MODEL_SCRIPT) $(TRAIN_RESULTS_YML) $(COMBINED_TEST_FILE_NAME) $(MODEL_FILE_NAME) $(COMBINED_TRAIN_FILE_NAME) $(TEST_RESULTS_FILE) $(TEST_FEATURES_FILE) $(TEST_SPECTRUM_FILE)

step4:
	@echo "**** STEP 7: CREATING INDOMAIN VERSION"
	python $(COMBINED_MODEL_SCRIPT) $(TEST_SPECTRUM_FILE) $(PREFIX) $(DOMAIN_PRIME_FILE) "" "" "" $(DOMAIN_OUTPUT_FILE)
