DATA_DIR=/projects/bhandare/workspace/PySG/data
PROJECTS_DIR=/projects/bhandare

COMBINED_TRAIN_FILE_NAME=$(wildcard GSM*train*.txt)
COMBINED_TEST_FILE_NAME=$(wildcard GSM*test*.txt)


MODEL_FILE_NAME=$(wildcard *Model.dat)
TRAIN_KSPECTRUM_FILE=$(wildcard *kspectrum.dat)
TRAIN_PARAMS_FILE=$(wildcard *params.dat)


CONF_TRAIN_PREFIX=TTP_InDomain_Train
CONF_TRAIN_YML=$(CONF_TRAIN_PREFIX).yml

TRAIN_FEATURES_FILE=$(wildcard *Train_Features*.dat)

CONF_TEST_PREFIX=TTP_InDomain_Test
CONF_TEST_YML=$(CONF_TEST_PREFIX).yml

TRAIN_RESULTS_YML=$(CONF_TRAIN_PREFIX)_Results.yml

CREATE_MODEL_SCRIPT=/projects/bhandare/workspace/kernels/k-spectrum/scripts/createBestModel.py

TEST_RESULTS_FILE=$(CONF_TEST_PREFIX)_Results.yml
TEST_FEATURES_FILE=$(CONF_TEST_PREFIX)_Features.txt

TEST_MODEL_SCRIPT=/projects/bhandare/workspace/kernels/k-spectrum/scripts/InDomainTest.py
SPLIT_SCRIPT=/projects/bhandare/workspace/scripts/SplitTrain/SplitTrainAndTest.py

RESULT_DIR=`date +'%d-%b-%Y'`

all: step1 step2 step3
.PHONY: all

step1:
	@echo "**** STEP 4: CREATE TRAIN CONF FILE ****"
	python CreateConfFile.py $(COMBINED_TRAIN_FILE_NAME) $(CONF_TRAIN_PREFIX) $(CONF_TRAIN_YML)

step2:
	@echo "**** STEP 5: CREATE MODEL ****"
	python $(CREATE_MODEL_SCRIPT) $(CONF_TRAIN_YML)

step3:
	@echo "**** STEP 6: TEST MODEL ****: "	
	python $(TEST_MODEL_SCRIPT) $(TRAIN_RESULTS_YML) $(COMBINED_TEST_FILE_NAME) $(MODEL_FILE_NAME) $(COMBINED_TRAIN_FILE_NAME) $(TEST_RESULTS_FILE) $(TEST_FEATURES_FILE)

step7:
	mkdir -p $(RESULT_DIR)
	mv $(POS_TRAIN_FILENAME) $(POS_TEST_FILENAME) $(RESULT_DIR)
	mv $(NEG_TRAIN_FILENAME) $(NEG_TEST_FILENAME) $(RESULT_DIR)
	mv $(COMBINED_TRAIN_FILE_NAME) $(RESULT_DIR)
	mv $(COMBINED_TEST_FILE_NAME) $(RESULT_DIR)
	mv $(TRAIN_RESULTS_YML) $(RESULT_DIR)
	mv $(TEST_RESULTS_FILE) $(RESULT_DIR)
	mv $(TEST_FEATURES_FILE) $(RESULT_DIR)
	mv $(CONF_TRAIN_YML) $(RESULT_DIR)
	mv $(MODEL_FILE_NAME) $(RESULT_DIR)
	mv $(TRAIN_KSPECTRUM_FILE) $(RESULT_DIR)
	mv $(TRAIN_PARAMS_FILE) $(RESULT_DIR)
	mv $(TRAIN_FEATURES_FILE) $(RESULT_DIR)

	git add $(RESULT_DIR)
	git add $(RESULT_DIR)/*