POS_TRAIN_FILENAME=to_ucsc.fp_0.05.filtered.hg19.elavl1_conservative_strand_train.fa
POS_TEST_FILENAME=to_ucsc.fp_0.05.filtered.hg19.elavl1_conservative_strand_test.fa

NEG_TRAIN_FILENAME=NONto_ucsc.fp_0.05.filtered.hg19.elavl1_conservative_strand_train.fa
NEG_TEST_FILENAME=NONto_ucsc.fp_0.05.filtered.hg19.elavl1_conservative_strand_test.fa

COMBINED_TRAIN_FILE_NAME=$(wildcard to_ucsc*_train*CompleteSet.txt)
COMBINED_TEST_FILE_NAME=$(wildcard to_ucsc*_test*.txt)


CONF_TRAIN_PREFIX=HuR_InDomain_Train
CONF_TRAIN_YML=$(CONF_TRAIN_PREFIX).yml

CONF_TEST_PREFIX=HuR_InDomain_Test
CONF_TEST_YML=$(CONF_TEST_PREFIX).yml

MODEL_FILE_NAME=$(CONF_TRAIN_PREFIX)_Model.dat
TRAIN_KSPECTRUM_FILE=$(CONF_TRAIN_PREFIX)_kspectrum.dat
TRAIN_PARAMS_FILE=$(CONF_TRAIN_PREFIX)_params.dat
TRAIN_RESULTS_YML=$(CONF_TRAIN_PREFIX)_Results.yml
TRAIN_FEATURES_FILE=$(CONF_TRAIN_PREFIX)_Features*.dat

TEST_RESULTS_FILE=$(CONF_TEST_PREFIX)_Results.yml
TEST_FEATURES_FILE=$(CONF_TEST_PREFIX)_Features.txt

RESULT_DIR=`date +'%d-%b-%Y'`


all: step1

step1:
	@echo "*** STEP 1: SAVING TO RESULT DIR, UPDATING GIT: $(RESULT_DIR)."
	mkdir -p $(RESULT_DIR)
	mv $(POS_TRAIN_FILENAME) $(POS_TEST_FILENAME) $(RESULT_DIR)
	mv $(NEG_TRAIN_FILENAME) $(NEG_TEST_FILENAME) $(RESULT_DIR)
	mv $(COMBINED_TRAIN_FILE_NAME) $(RESULT_DIR)	
	mv $(COMBINED_TEST_FILE_NAME) $(RESULT_DIR)
	mv $(TRAIN_RESULTS_YML) $(RESULT_DIR)
	mv $(TEST_RESULTS_FILE) $(RESULT_DIR)
	mv $(TEST_FEATURES_FILE) $(RESULT_DIR)
	mv $(CONF_TRAIN_YML) $(RESULT_DIR)
	mv $(MODEL_FILE_NAME) $(RESULT_DIR)
	mv $(TRAIN_KSPECTRUM_FILE) $(RESULT_DIR)
	mv $(TRAIN_PARAMS_FILE) $(RESULT_DIR)
	mv $(TRAIN_FEATURES_FILE) $(RESULT_DIR)

	git add $(RESULT_DIR)
	git add $(RESULT_DIR)/*
	git commit -m "Saving HuR results."
