DATA_DIR=../../data
PROJECTS_DIR=/projects/bhandare
KSPECTRUM_PIPELINE_DIR=$(PROJECTS_DIR)/k-spectrum-pipeline


POS_FILE=$(DATA_DIR)/HuR_TTP/ELAV1_Conservative_ZFP36.fa
NEG_FILE=$(DATA_DIR)/HuR_TTP/OnlyELAV1_OnlyZFP36.fa

COMBINED_FILE_NAME=ELAV1_Conservative_ZFP36_OnlyELAV1_OnlyZFP36_467_7367_CompleteSet.txt
COMBINED_FILE=$(DATA_DIR)/HuR_TTP/$(COMBINED_FILE_NAME)

FEATURE_FILE=$(DATA_DIR)/HuR_TTP/CommonvsOnlyHuRConservativeAndOnlyTTP_Features.dat

BASIC_KSPECTRUM_SCRIPT=$(PROJECTS_DIR)/workspace/kernels/k-spectrum/scripts/basic_kspectrum.py
TOP_KMERS_SCRIPT=$(PROJECTS_DIR)/workspace/scripts/extractTopFeatures.py

CONF_YML=$(DATA_DIR)/HuR_TTP/CommonvsOnlyHuRConservativeAndOnlyTTP.yml
RESULTS_DIR=$(date +%d-%b-%Y)

all: $(COMBINED_FILE) $(FEATURE_FILE)
.PHONY: all

$(COMBINED_FILE): $(POS_FILE) $(NEG_FILE) seq_counter.py 
	python seq_counter.py $(POS_FILE) $(NEG_FILE)
	mv $(COMBINED_FILE_NAME) $(DATA_DIR)/HuR_TTP/

$(FEATURE_FILE): $(COMBINED_FILE) $(BASIC_KSPECTRUM_SCRIPT) $(CONF_YML)
	echo $(COMBINED_FILE)
	python $(BASIC_KSPECTRUM_SCRIPT) $(CONF_YML)
	python $(TOP_KMERS_SCRIPT) $(FEATURE_FILE) 25 $(DATA_DIR)/HuR_TTP/$(FEATURE_FILE).topfeatures.txt
	mkdir -p $(RESULTS_DIR)
	mv $(RESULTS_DIR) $(DATA_DIR)/HuR_TTP/
	mv *Results.yml $(DATA_DIR)/HuR_TTP/$(RESULTS_DIR)/
	mv *.dat $(DATA_DIR)/HuR_TTP/$(RESULTS_DIR)/



