TTP Basic k-spectrum:

pos_file=/projects/bhandare/workspace/PySG/data/TTP/GSM1286117_ZFP36_clusters_stranded.fa 
neg_file=/projects/bhandare/workspace/PySG/data/TTP/NONGSM1286117_ZFP36_clusters_stranded.fa 
conf_prefix=TTP_Basic

HuR Basic k-spectrum:
pos_file=/projects/bhandare/workspace/PySG/data/HuR/to_ucsc.fp_0.05.filtered.hg19.elavl1_conservative_strand.fa
neg_file=/projects/bhandare/workspace/PySG/data/HuR/NONto_ucsc.fp_0.05.filtered.hg19.elavl1_conservative_strand.fa
conf_prefix=HuR_Basic

CommonvsHuRAndTTP:
pos_file=/projects/bhandare/workspace/PySG/data/HuR_TTP/faFromBed/HuR_TTP_Common_Clusters.fa
neg_file=/projects/bhandare/workspace/PySG/data/HuR_TTP/faFromBed/Only_HuR_And_Only_TTP_Clusters.fa
conf_prefix=CommonvsHuRAndTTP

OnlyHuRvsCommonAndTTP:
pos_file=/projects/bhandare/workspace/PySG/data/HuR_TTP/faFromBed/Only_HuR_Clusters.fa
neg_file=/projects/bhandare/workspace/PySG/data/HuR_TTP/faFromBed/Only_TTP_And_HuR_TTP_Common_Clusters.fa
conf_prefix=OnlyHuRvsCommonAndTTP

OnlyHuRvsOnlyTTP:
pos_file=/projects/bhandare/workspace/PySG/data/HuR_TTP/faFromBed/Only_HuR_Clusters.fa
neg_file=/projects/bhandare/workspace/PySG/data/HuR_TTP/faFromBed/Only_TTP_Clusters.fa
conf_prefix=OnlyHuRvsOnlyTTP

OnlyTTPvsCommonAndHuR:
pos_file=/projects/bhandare/workspace/PySG/data/HuR_TTP/faFromBed/Only_TTP_Clusters.fa
neg_file=/projects/bhandare/workspace/PySG/data/HuR_TTP/faFromBed/Only_HuR_And_HuR_TTP_Common_Clusters.fa
conf_prefix=OnlyTTPvsCommonAndHuR


HuRTrain_HuRTest:

pos_file=/projects/bhandare/workspace/PySG/data/HuR/to_ucsc.fp_0.05.filtered.hg19.elavl1_conservative_strand.fa
neg_file=/projects/bhandare/workspace/PySG/data/HuR/NONto_ucsc.fp_0.05.filtered.hg19.elavl1_conservative_strand.fa
conf_prefix=HuR_Basic

CommonvsHuRAndTTP:
pos_file=/projects/bhandare/workspace/PySG/data/HuR_TTP/faFromBed/HuR_TTP_Common_Clusters.fa
neg_file=/projects/bhandare/workspace/PySG/data/HuR_TTP/faFromBed/Only_HuR_And_Only_TTP_Clusters.fa
conf_prefix=CommonvsHuRAndTTP

OnlyHuRvsCommonAndTTP:
pos_file=/projects/bhandare/workspace/PySG/data/HuR_TTP/faFromBed/Only_HuR_Clusters.fa
neg_file=/projects/bhandare/workspace/PySG/data/HuR_TTP/faFromBed/Only_TTP_And_HuR_TTP_Common_Clusters.fa
conf_prefix=OnlyHuRvsCommonAndTTP

OnlyHuRvsOnlyTTP:
pos_file=/projects/bhandare/workspace/PySG/data/HuR_TTP/faFromBed/Only_HuR_Clusters.fa
neg_file=/projects/bhandare/workspace/PySG/data/HuR_TTP/faFromBed/Only_TTP_Clusters.fa
conf_prefix=OnlyHuRvsOnlyTTP

HuRInDomain:
pos_file=/projects/bhandare/workspace/PySG/data/HuR/to_ucsc.fp_0.05.filtered.hg19.elavl1_conservative_strand.fa
neg_file=/projects/bhandare/workspace/PySG/data/HuR/NONto_ucsc.fp_0.05.filtered.hg19.elavl1_conservative_strand.fa
pos_train_file=/projects/bhandare/workspace/PySG/data/HuR/to_ucsc.fp_0.05.filtered.hg19.elavl1_conservative_strand_train.fa
neg_train_file=/projects/bhandare/workspace/PySG/data/HuR/NONto_ucsc.fp_0.05.filtered.hg19.elavl1_conservative_strand_train.fa
pos_test_file=/projects/bhandare/workspace/PySG/data/HuR/to_ucsc.fp_0.05.filtered.hg19.elavl1_conservative_strand_test.fa
neg_test_file=/projects/bhandare/workspace/PySG/data/HuR/NONto_ucsc.fp_0.05.filtered.hg19.elavl1_conservative_strand_test.fa
conf_train_prefix=HuR_InDomain_Train
conf_test_prefix=HuR_InDomain_Test

TTPInDomain:
